desimaster/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView
from videos.sitemaps import StaticViewSitemap, VideoSitemap, CategorySitemap, SubCategorySitemap

sitemaps = {
    'static': StaticViewSitemap,
    'videos': VideoSitemap,
    'categories': CategorySitemap,
    'subcategories': SubCategorySitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('videos.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

videos/urls.py
from django.urls import path
from . import views

app_name = 'videos'

urlpatterns = [
    path('', views.home, name='home'),
    path('video/<int:video_id>/', views.video_player, name='video_player'),
    path('category/<int:category_id>/', views.video_list, name='video_list'),
    path('category/<int:category_id>/subcategory/<int:subcategory_id>/', views.video_list, name='video_list'),
    path('category/', views.video_list, {'category_id': None}, name='video_list_all'),
    path('upload/', views.upload_video, name='upload_video'),
]

videos/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class SubCategory(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Video(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    video_file = models.FileField(upload_to='videos/')
    thumbnail = models.ImageField(upload_to='thumbnails/', null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    subcategory = models.ForeignKey(SubCategory, on_delete=models.SET_NULL, null=True, blank=True)
    tags = models.ManyToManyField(Tag, blank=True)
    duration = models.DurationField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    related_videos = models.ManyToManyField('self', blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('videos:video_player', args=[str(self.id)])
    

videos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404
from .models import Video, Category, SubCategory, Tag
from .utils import transcode_video
import os
from django.http import HttpResponse


def upload_video(request):
    if request.method == 'POST':
        title = request.POST['title']
        description = request.POST['description']
        category_id = request.POST['category']
        subcategory_id = request.POST.get('subcategory')
        tags_ids = request.POST.getlist('tags')  # Assuming multiple tags can be selected
        video_file = request.FILES['video_file']
        thumbnail = request.FILES.get('thumbnail')
        duration = request.POST.get('duration')  # Assuming duration is provided

        category = Category.objects.get(id=category_id)
        subcategory = SubCategory.objects.get(id=subcategory_id) if subcategory_id else None
        tags = Tag.objects.filter(id__in=tags_ids)
        
        video = Video.objects.create(
            title=title,
            description=description,
            video_file=video_file,
            thumbnail=thumbnail,
            category=category,
            subcategory=subcategory,
            duration=duration
        )
        video.tags.set(tags)

        video_dir = os.path.join('media', 'videos', str(video.id))
        os.makedirs(video_dir, exist_ok=True)

        input_video_path = os.path.join('media', video.video_file.name)
        transcode_video(input_video_path, video_dir)

        return redirect('videos:home')

    categories = Category.objects.all()
    subcategories = SubCategory.objects.all()
    tags = Tag.objects.all()
    context = {
        'categories': categories,
        'subcategories': subcategories,
        'tags': tags,
    }
    return render(request, 'upload_video.html', context)

def home(request):
    categories = Category.objects.all()
    latest_videos = Video.objects.order_by('-created_at')
    search_query = request.GET.get('q')

    if search_query:
        latest_videos = latest_videos.filter(title__icontains=search_query)

    paginator = Paginator(latest_videos, 21)  # Show 6 videos per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'categories': categories,
        'latest_videos': page_obj,
        'search_query': search_query,
    }
    return render(request, 'home.html', context)

def video_list(request, category_id=None):
    videos = Video.objects.order_by('-created_at')
    category = None
    search_query = request.GET.get('q')

    if category_id:
        category = get_object_or_404(Category, id=category_id)
        videos = videos.filter(category=category)

    if search_query:
        videos = videos.filter(title__icontains=search_query)

    paginator = Paginator(videos, 21)  # Show 2 videos per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'videos': page_obj,
        'category': category,
        'search_query': search_query,
    }

    return render(request, 'video_list.html', context)


def video_player(request, video_id):
    video = get_object_or_404(Video, id=video_id)
    video_dir = os.path.join('media', 'videos', str(video.id))
    resolutions = []

    # Check if the video directory exists
    if os.path.exists(video_dir):
        # Get the paths of the video files
        for filename in os.listdir(video_dir):
            if filename.endswith('.mp4'):
                video_url = os.path.join('media', 'videos', str(video.id), filename)
                resolutions.append({'width': None, 'height': None, 'video_url': video_url})
    else:
        # Handle the case when the video directory does not exist
        print(f"Error: Video directory not found for video ID {video.id}")
        # You can add additional error handling or fallback logic here

    # If no video files are available, use the original video file
    if not resolutions:
        resolutions.append({'width': None, 'height': None, 'video_url': video.video_file.url})

    # Fetch related videos
    related_videos = video.related_videos.all()

    # Pagination
    paginator = Paginator(related_videos, 9)  # 10 items per page
    page = request.GET.get('page')
    try:
        related_videos_paginated = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        related_videos_paginated = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        related_videos_paginated = paginator.page(paginator.num_pages)

    context = {
        'video': video,
        'resolutions': resolutions,
        'related_videos': related_videos_paginated,  # Pass paginated related videos to the context
    }

    return render(request, 'videos/video_player.html', context)

def robots_txt(request):
    lines = [
        "User-agent: *",
        "Disallow:",
    ]
    return HttpResponse("\n".join(lines), content_type="text/plain")

videos/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Desi Premium Sex videos - Free OnlyFans Videos | Mygoad</title>
    <meta name="description" content="Watch free premium sex videos and exclusive OnlyFans content. Enjoy high-definition adult entertainment for free on Desibcz.">

    <link rel="canonical" href="">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
   
</head>
<body>
 
    {% include "nav.html" %} 
    <div class="container my-4">
        {% block content %}{% endblock %}
    </div>
   
   
    <footer class="footer bg-dark text-light py-3">
        
              <p class="footer-text">© 2024 All Rights Reserved</p>
           
      </footer>
    <script src="{% static 'js/menu.js' %}"></script>
<!-- Load Bootstrap 5 and Popper.js (bundled together) -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>

</body>
</html>

videos/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form class="search-form" method="get" action="{% url 'videos:home' %}">
    <div class="input-group">
      <input type="text" class="form-control search-input" name="q" placeholder="Search Videos" aria-label="Search" value="{{ search_query|default_if_none:'' }}">
      <div class="input-group-append">
        <button class="btn btn-outline-secondary search-btn" type="submit">Search</button>
      </div>
    </div>
  </form>
  <div class="content">
    Premium Desi Videos
    <div class="slider">
      <div class="slide-anim">
        <div class="slide slide1">Free</div>
        <div class="slide slide2">OnlyFans</div>
        <div class="slide slide3">Tango</div>
        <div class="slide slide1">Viral</div>
      </div>
    </div>
  </div>
  <div class="row">
    {% for video in latest_videos %}
    <div class="col-md-4">
        <div class="video-thumbnail">
            {% if video.thumbnail %}
                <a href="{% url 'videos:video_player' video.id %}">
                    <img src="{{ video.thumbnail.url }}" alt="{{ video.title }}">
                </a>
                <p class="video-title">{{ video.title }}</p>
                {% if video.duration %}
                <p class="video-duration"><img src="{% static 'images/clock-icon.png' %}" alt="Clock Icon"> {{ video.duration }}</p>

                {% else %}
                    <p class="video-duration">Duration not available</p>
                {% endif %}
            {% else %}
                <p class="video-title">No thumbnail available</p>
            {% endif %}
        </div>
    </div>
    {% endfor %}
</div>


{% if latest_videos.has_other_pages %}
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if latest_videos.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ latest_videos.previous_page_number }}{% if category %}&category={{ category.id }}{% endif %}">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">Previous</span>
        </li>
        {% endif %}

        {% for page_num in latest_videos.paginator.page_range %}
        {% if page_num == latest_videos.number %}
        <li class="page-item">
            <span class="page-link active">{{ page_num }}</span>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}{% if category %}&category={{ category.id }}{% endif %}">{{ page_num }}</a>
        </li>
        {% endif %}
        {% endfor %}

        {% if latest_videos.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ latest_videos.next_page_number }}{% if category %}&category={{ category.id }}{% endif %}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">Next</span>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}
{% endblock %}

videos/templates/nav.html
{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container">
      <!-- Left side: Text logo -->
      <a id="brand" class="navbar-brand" href="{% url 'videos:home' %}">My<em>goad</em></a>
  
      <!-- Center: Search box -->
     
      
      <!-- Right side: Menu button -->
      <button id="showMenuBtn" class="btn btn-outline-light">Category</button>
    </div>
  </nav>


<!-- Side menu -->
<div id="sideMenu" class="side-menu">
    <button id="closeMenuBtn" class="btn btn-outline-danger close-btn">&times;</button>
    <ul class="navbar-nav">
        <li class="nav-item" id="all-bt">
            <a id="all-btn" class="nav-link" href="{% url 'videos:video_list_all' %}">All Videos</a>
        </li>
        {% for category in categories %}
        <li class="nav-item">
            <div class="main-category">
                <a id="all-btn" class="nav-link category-link" href="#">{{ category.name }}</a>
                {% if category.subcategory_set.all %}
                <span class="dropdown-icon">&#9660;</span>
                {% endif %}
            </div>
            <ul class="submenu">
                {% for subcategory in category.subcategory_set.all %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'videos:video_list' category_id=subcategory.category_id %}">{{ subcategory.name }}</a>
                </li>
                {% endfor %}
            </ul>
        </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

videos/templates/video_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<form class="search-form" method="get" action="{% url 'videos:home' %}">
    <div class="input-group">
      <input type="text" class="form-control search-input" name="q" placeholder="Search Videos" aria-label="Search" value="{{ search_query|default_if_none:'' }}">
      <div class="input-group-append">
        <button class="btn btn-outline-secondary search-btn" type="submit">Search</button>
      </div>
    </div>
  </form>
<h1 id="alltitel"  class="mb-4">{% if category %}{{ category.name }} Videos{% else %}All Videos{% endif %}</h1>
<div class="row">
    {% for video in videos %}
    <div class="col-md-4">
        <div class="video-thumbnail">
            {% if video.thumbnail %}
                <a href="{% url 'videos:video_player' video.id %}">
                    <img src="{{ video.thumbnail.url }}" alt="{{ video.title }}">
                </a>
                <p class="video-title">{{ video.title }}</p>
                {% if video.duration %}
                <p class="video-duration"><img src="{% static 'images/clock-icon.png' %}" alt="Clock Icon"> {{ video.duration }}</p>

                {% else %}
                    <p class="video-duration">Duration not available</p>
                {% endif %}
            {% else %}
                <p class="video-title">No thumbnail available</p>
            {% endif %}
        </div>
    </div>
    {% endfor %}
</div>

{% if videos.has_other_pages %}
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if videos.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ videos.previous_page_number }}{% if category %}&category={{ category.id }}{% endif %}">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">Previous</span>
        </li>
        {% endif %}

        {% for page_num in videos.paginator.page_range %}
        {% if page_num == videos.number %}
        <li class="page-item">
            <span class="page-link active">{{ page_num }}</span>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}{% if category %}&category={{ category.id }}{% endif %}">{{ page_num }}</a>
        </li>
        {% endif %}
        {% endfor %}

        {% if videos.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ videos.next_page_number }}{% if category %}&category={{ category.id }}{% endif %}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">Next</span>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}
{% endblock %}

videos/templates/videos/video_player.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ video.title }} - Mygoad</title>
    <meta name="description" content="{{ video.description }}">
    <meta property="og:title" content="{{ video.title }}">
    <meta property="og:description" content="{{ video.description }}">
    <meta property="og:type" content="video.other">
    <meta property="og:url" content="{{ request.build_absolute_uri }}">
    <meta property="og:image" content="{{ video.thumbnail_url }}"> <!-- Add thumbnail URL if available -->
    <meta name="keywords" content="{% for tag in video.tags.all %}{{ tag.name }}{% if not forloop.last %}, {% endif %}{% endfor %}">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-black">
    <div class="container">
      <!-- Left side: Text logo -->
      <a id="brand"  class="navbar-brand" href="{% url 'videos:home' %}">My<em>goad</em></a>
  
      <!-- Center: Search box -->
      
      
  
      <!-- Right side: Menu button -->
      <a id="showMenuBtn" class="btn btn-outline-light" href="{% url 'videos:video_list_all' %}">All Videos</a>
    
    </div>
  </nav>


<!-- Side menu -->

<div class="container my-4">
    <form class="search-form" method="get" action="{% url 'videos:home' %}">
        <div class="input-group">
            <input type="text" class="form-control search-input" name="q" placeholder="Search Videos" aria-label="Search" value="{{ search_query|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary search-btn" type="submit">Search</button>
            </div>
        </div>
    </form>

    <div class="video-details-box">
        <video controls>
            {% for resolution in resolutions %}
                {% if resolution.width and resolution.height %}
                    <source src="{{ resolution.video_url }}" type="video/mp4" res="{{ resolution.width }}x{{ resolution.height }}">
                {% else %}
                    <source src="{{ resolution.video_url }}" type="video/mp4">
                {% endif %}
            {% endfor %}
        </video>
       
            <h1>{{ video.title }}</h1>
            <p>{{ video.description }}</p>
           <div class="tag-list">
                <ul>
                    {% for tag in video.tags.all %}
                        <li>{{ tag.name }}</li>
                    {% endfor %}
                </ul>
            </div>
         
    </div>


</div>



<div class="container my-4">
    <h2 class="related">Related Videos</h2>
    <div class="row">
        {% for related_video in related_videos %}
        <div class="col-md-4">
          <div class="video-thumbnail">
              {% if related_video.thumbnail %}
                  <a href="{% url 'videos:video_player' related_video.id %}">
                      <img src="{{ related_video.thumbnail.url }}" alt="{{ related_video.title }}">
                  </a>
                  <p class="video-title">{{ related_video.title }}</p>
                  {% if related_video.duration %}
                  <p class="video-duration"><img src="{% static 'images/clock-icon.png' %}" alt="Clock Icon"> {{ related_video.duration }}</p>
                  {% else %}
                      <p class="video-duration">Duration not available</p>
                  {% endif %}
              {% else %}
                  <p class="video-title">No thumbnail available</p>
              {% endif %}
          </div>
      </div>
        {% endfor %}
    </div>
  </div>

{% if related_videos.has_other_pages %}
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if related_videos.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ related_videos.previous_page_number }}{% if category %}&category={{ category.id }}{% endif %}">Previous</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">Previous</span>
        </li>
        {% endif %}

        {% for page_num in related_videos.paginator.page_range %}
        {% if page_num == related_videos.number %}
        <li class="page-item ">
            <span class="page-link active">{{ page_num }}</span>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_num }}{% if category %}&category={{ category.id }}{% endif %}">{{ page_num }}</a>
        </li>
        {% endif %}
        {% endfor %}

        {% if related_videos.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ related_videos.next_page_number }}{% if category %}&category={{ category.id }}{% endif %}">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">Next</span>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}

<footer class="footer bg-dark text-light py-3">
        
    <p class="footer-text">© 2024 All Rights Reserved</p>
 
</footer>
<script src="{% static 'js/player.js' %}"></script>
<script src="{% static 'js/menu.js' %}"></script>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
<script type='text/javascript' src='//pl24182477.cpmrevenuegate.com/f1/ec/ac/f1ecacd7c4ad5b97e6048e01ab89f97a.js'></script>
</body>
</html>